spring.datasource.url=jdbc:mysql://localhost:3306/db_iwallet?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
jwt.secret=IWalletJwtSecretKeyChangeThisToANewLongRandomValueForProduction1234567890